project:
  title: "Statistical Genetics"
  type: website
  output-dir: docs

website:
  title: "Statistical Genetics"
  favicon: course_logo.png
  sidebar:
    pinned: true
    background: "#033C5A"
    foreground: white 
    border: true
    logo: course_logo.png
    style: docked
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Schedule
        icon: calendar
      - href: syllabus.qmd
        text: Syllabus
        icon: book
      - href: faq.qmd
        text: "FAQ"
        icon: question
      - href: https://github.com/gwcbi/StatGen
        text: "GitHub"
        icon: github
        target: _blank 
      - href: https://www.zotero.org/groups/6113424/pubh-8878/library
        text: "Zotero Library"
        icon: book
        target: _blank
format:
  html:
    grid:
      sidebar-width: 250px
    css: styles.css
    toc: true
    mainfont: system-ui, sans-serif
    linkcolor: "#0190DB"



