project:
  type: website
  output-dir: docs

website:
  title: "Statistical Genetics"
  sidebar:
    pinned: true
    logo: course_logo.png
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Schedule
        icon: calendar
      - href: syllabus.qmd
        text: Syllabus
        icon: book
      - href: https://github.com/gwcbi/StatGen
        text: "GitHub"
        icon: github
        target: _blank 
format:
  html:
    grid:
      sidebar-width: 200px
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true
    mainfont: Avenir Next LT Pro, Avenir Next, Avenir, sans-serif



