---
title: "Schedule"
subtitle: "PUBH 8878, Fall '25"
page-layout: full
---

+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| Week       | Lecture                                                                            | Readings                                                                                     | Assignment                                      |
+============+====================================================================================+==============================================================================================+=================================================+
| 1          | [Foundations: Mendelian genetics & statistical basics](lectures/lecture-01.qmd)    | **Required:**                                                                                | [Problem Set 01](assignments/assignment-01.qmd) |
|            |                                                                                    |                                                                                              |                                                 |
|            |                                                                                    | -   Sorensen 1.1-1.3                                                                         |                                                 |
|            |                                                                                    | -   Laird Chapters 1-3                                                                       |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 2          | [Heritability, segregation, and the gene-mapping toolkit](lectures/lecture-02.qmd) | **Required**:                                                                                |                                                 |
|            |                                                                                    |                                                                                              |                                                 |
|            |                                                                                    | -   Sorensen Chapter 2                                                                       |                                                 |
|            |                                                                                    | -   Laird Chapters 4-5                                                                       |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 3          | Likelihood algorithms & practical gene mapping                                     |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 4          | Population structure & Bayesian fundamentals                                       |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 5          | MCMC in practice & GWAS design issues                                              |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 6          | Prediction I – Linear models & shrinkage methods                                   |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 7          |  Multiple testing & false-discovery control                                        |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 8          | Binary traits and family-based association tests                                   |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 9          | Prediction II – Model Checking and non-parametric methods                          |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 10         | Advanced AI Topics in Statistical Genetics: Language Models for Genomics           | **Recommended:**                                                                             |                                                 |
|            |                                                                                    |                                                                                              |                                                 |
|            |                                                                                    | -   [Ji et al., 2021](https://academic.oup.com/bioinformatics/article/37/15/2112/6128680)    |                                                 |
|            |                                                                                    | -   [Avsec et al., 2021](https://www.nature.com/articles/s41592-021-01252-x)                 |                                                 |
|            |                                                                                    | -   [Cheng et al., 2023](https://www.science.org/doi/10.1126/science.adg7492)                |                                                 |
|            |                                                                                    | -   [Baghbanzadeh et al., 2025](https://www.biorxiv.org/content/10.1101/2025.03.12.642848v1) |                                                 |
|            |                                                                                    | -   [Mollerus et al., 2025](https://www.biorxiv.org/content/10.1101/2025.07.08.663767v1)     |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+
| 11         |                                                                                    |                                                                                              |                                                 |
+------------+------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+-------------------------------------------------+